// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calcModifiedPeptidePCpp
std::vector<double> calcModifiedPeptidePCpp(std::vector<std::string> ModifiedSequences, std::vector<std::string> PhosphoProbabilitySequences, std::vector<std::string> OxProbabilitySequences);
RcppExport SEXP xavamess_calcModifiedPeptidePCpp(SEXP ModifiedSequencesSEXP, SEXP PhosphoProbabilitySequencesSEXP, SEXP OxProbabilitySequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ModifiedSequences(ModifiedSequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type PhosphoProbabilitySequences(PhosphoProbabilitySequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type OxProbabilitySequences(OxProbabilitySequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(calcModifiedPeptidePCpp(ModifiedSequences, PhosphoProbabilitySequences, OxProbabilitySequences));
    return rcpp_result_gen;
END_RCPP
}
// constructModifiedPeptide
CharacterVector constructModifiedPeptide(CharacterVector ModifiedSequences, IntegerVector positions, std::string delimiter);
RcppExport SEXP xavamess_constructModifiedPeptide(SEXP ModifiedSequencesSEXP, SEXP positionsSEXP, SEXP delimiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ModifiedSequences(ModifiedSequencesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type positions(positionsSEXP);
    Rcpp::traits::input_parameter< std::string >::type delimiter(delimiterSEXP);
    rcpp_result_gen = Rcpp::wrap(constructModifiedPeptide(ModifiedSequences, positions, delimiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"xavamess_calcModifiedPeptidePCpp", (DL_FUNC) &xavamess_calcModifiedPeptidePCpp, 3},
    {"xavamess_constructModifiedPeptide", (DL_FUNC) &xavamess_constructModifiedPeptide, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_xavamess(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
