// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calcModifiedPeptideP
std::vector<double> calcModifiedPeptideP(std::vector<std::string> ModifiedSequences, std::vector<std::string> PhosphoProbabilitySequences, std::vector<std::string> OxProbabilitySequences);
RcppExport SEXP xavamess_calcModifiedPeptideP(SEXP ModifiedSequencesSEXP, SEXP PhosphoProbabilitySequencesSEXP, SEXP OxProbabilitySequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ModifiedSequences(ModifiedSequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type PhosphoProbabilitySequences(PhosphoProbabilitySequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type OxProbabilitySequences(OxProbabilitySequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(calcModifiedPeptideP(ModifiedSequences, PhosphoProbabilitySequences, OxProbabilitySequences));
    return rcpp_result_gen;
END_RCPP
}
