# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate modified peptide probability
#' @description Integrates the Modification Probabilities from MaxQuant into a localization probability of the peptide
#' @param ModifiedSequences the "Modified Sequence" column in evidence.txt
#' @param PhosphoProbabilitySequences the "Phospho (STY) Probabilities" column in evidence.txt
#' @param ModifiedSequences the "Oxidation (M) Probabilities" column in evidence.txt
#' @return the numeric probabilities
#' @useDynLib xavamess
#' @importFrom Rcpp evalCpp
#' @examples
#' calcPhosphoP("_(ac)AGDS(ph)DSWDADAFSVEDPVRK_", "AGDS(1)DSWDADAFSVEDPVRK", "")
#' calcPhosphoP("_AAFNSGKVDIVAINDPFIDLNYM(ox)VYM(ox)FQYDSTHGK_", "", "AAFNSGKVDIVAINDPFIDLNYM(1)VYM(1)FQYDSTHGK")
#' calcPhosphoP("_AAEM(ox)CY(ph)RK_", "AAEMCY(1)RK", "AAEM(1)CYRK")
#'
#'
#' calcPhosphoP("_AGDSDSWDADAM(ox)SVEDPVRK_", "AGDSDSWDADAM(1)SVEDPVRK", "")
#' calcPhosphoP("_(ac)AGDS(ph)DS(ph)WDADAFSVEDPVRK_", "AGDS(0.995)DS(0.998)WDADAFS(0.007)VEDPVRK", 2)
#' calcPhosphoP("_(ac)AGDS(ph)DSWDADAFSVEDPVRS(ph)_", "AGDS(0.995)DS(0.998)WDADAFS(0.007)VEDPVRS(1)", 2)
#' @export
calcModifiedPeptideP <- function(ModifiedSequences, PhosphoProbabilitySequences, OxProbabilitySequences) {
    .Call('xavamess_calcModifiedPeptideP', PACKAGE = 'xavamess', ModifiedSequences, PhosphoProbabilitySequences, OxProbabilitySequences)
}

