# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate modified peptide probability
#' @description Integrates the Modification Probabilities from MaxQuant into a localization probability of the peptide
#' @param ModifiedSequences the "Modified Sequence" column in evidence.txt
#' @param PhosphoProbabilitySequences the "Phospho (STY) Probabilities" column in evidence.txt
#' @param OxProbabilitySequences the "Oxidation (M) Probabilities" column in evidence.txt
#' @return the numeric probabilities
#' @useDynLib xavamess
#' @importFrom Rcpp evalCpp
#' @examples
#' calcModifiedPeptideP("_(ac)AGDS(ph)DSWDADAFSVEDPVRK_", "AGDS(1)DSWDADAFSVEDPVRK", "")
#' calcModifiedPeptideP("_AAFNSGKVDIVAINDPFIDLNYM(ox)VYM(ox)FQYDSTHGK_", "",
#'                      "AAFNSGKVDIVAINDPFIDLNYM(1)VYM(1)FQYDSTHGK")
#' calcModifiedPeptideP("_AAEM(ox)CY(ph)RK_", "AAEMCY(1)RK", "AAEM(1)CYRK")
#'
#' # Also vectorized:
#' calcModifiedPeptideP(
#'                      c("_AAEM(ox)CY(ph)RK_", "_(ac)AGDS(ph)DSWDADAFSVEDPVRS(ph)_",
#'                        "_(ac)AGDS(ph)DSWDADAFSVEDPVRM(ox)_"),
#'                      c("AAEMCY(0.99)RK", "AGDS(0.995)DSWDADAFS(0.007)VEDPVRS(0.998)",
#'                        "AGDS(0.995)DSWDADAFS(0.007)VEDPVRM"),
#'                      c("AAEM(0.87)CYRK", "", "AGDSDSWDADAFSVEDPVRM(0.998)"))
#' @export
calcModifiedPeptideP <- function(ModifiedSequences, PhosphoProbabilitySequences, OxProbabilitySequences) {
    .Call('xavamess_calcModifiedPeptideP', PACKAGE = 'xavamess', ModifiedSequences, PhosphoProbabilitySequences, OxProbabilitySequences)
}

#' Construct the modified peptide sequence as a string
#' @description Takes the Modified Sequence from MaxQuant and turns it into a string of the form a;T_12;M_72.
#' @param ModifiedSequences the "Modified Sequence" column in evidence.txt
#' @param positions the peptides start positions within the protein. Recycled according to the standard rules if necessary, with a warning.
#' @param delimiter an optional delimiter to separate the modifications within one peptide
#' @return the modifications string
#' @useDynLib xavamess
#' @importFrom Rcpp evalCpp
#' @examples
#' constructModifiedPeptide("_(ac)AGDS(ph)DSWDADAFSVEDPVRK_", 1)
#' constructModifiedPeptide("_AAFNSGKVDIVAINDPFIDLNYM(ox)VYM(ox)FQYDSTHGK_", 20)
#' constructModifiedPeptide("_AAEM(ox)CY(ph)RK_", 10, ":")
#'
#' # Also vectorized:
#' constructModifiedPeptide(c("_(ac)AGDS(ph)DSWDADAFSVEDPVRK_",
#'                        "_AAFNSGKVDIVAINDPFIDLNYM(ox)VYM(ox)FQYDSTHGK_",
#'                        "_AAEM(ox)CY(ph)RK_"), c(1, 20, 10), "+")
#' @export
constructModifiedPeptide <- function(ModifiedSequences, positions = integer(), delimiter = ";") {
    .Call('xavamess_constructModifiedPeptide', PACKAGE = 'xavamess', ModifiedSequences, positions, delimiter)
}

